name: Build & Publish Debian APT Repo

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Debian packages
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: "--build=binary --no-sign"

      - name: Show built debs
        run: ls -la debian/artifacts

      - name: Upload .deb artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: debian/artifacts/*.deb

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download .deb artifacts
        uses: actions/download-artifact@v4
        with:
          name: debs

      - name: Move .deb files to single folder
        run: |
          mkdir -p deb-output
          mv *.deb deb-output/
          echo "Debs in deb-output:"
          ls -la deb-output

      - name: List .deb files for repo action
        id: list_debs
        run: |
          # produce a newline-separated list of files
          ls deb-output > deb-files.txt
          cat deb-files.txt
          # store for next step
          echo "DEB_FILES=$(cat deb-files.txt | paste -sd '\n' -)" >> $GITHUB_ENV

      - name: Create APT repo (Debian Trixie amd64)
        uses: jrandiny/apt-repo-action@v2.0.1
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: amd64
          repo_supported_version: trixie
          file: ${{ env.DEB_FILES }}      # pass actual file names
          file_target_version: trixie
          page_branch: gh-pages
          repo_folder: repo
          private_key: ${{ secrets.APT_SIGNING_KEY || '' }}
          public_key: ${{ secrets.APT_SIGNING_PUBKEY || '' }}
          key_passphrase: ${{ secrets.APT_SIGNING_KEY_PASSPHRASE || '' }}
          debug: true

      - name: Show repo contents
        run: ls -R repo

      - name: Upload repo folder for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
